routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// use Illuminate\Routing\Route;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

// Route::get('/pertanyaan', 'PertanyaanController@index');

// Route::get('/pertanyaan/create', 'PertanyaanController@create');

// Route::post('/pertanyaan', 'PertanyaanController@store');

// Route::get('/pertanyaan/{pertanyaan_id}', 'PertanyaanController@show');

// Route::get('/pertanyaan/{pertanyaan_id}/edit', 'PertanyaanController@edit');

// Route::put('/pertanyaan/{pertanyaan_id}', 'PertanyaanController@update');

// Route::delete('/pertanyaan/{pertanyaan_id}', 'PertanyaanController@delete');

Route::resource('pertanyaan', 'NewPertanyaanController');
// Route::get('/pertanyaan', 'NewPertanyaanController@index');

// Route::get('/pertanyaan/create', 'PertanyaanController@create');

// Route::post('/pertanyaan', 'NewPertanyaanController@store');

// Route::get('/pertanyaan/{pertanyaan_id}', 'NewPertanyaanController@show');

// Route::get('/pertanyaan/{pertanyaan_id}/edit', 'NewPertanyaanController@edit');

// Route::put('/pertanyaan/{pertanyaan_id}', 'NewPertanyaanController@update');

// Route::delete('/pertanyaan/{pertanyaan_id}', 'NewPertanyaanController@destroy');

app/PertanyaanModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PertanyaanModel extends Model
{
    protected $table = 'tbl_pertanyaan';
    // protected $fillable = ["isi_pertanyaan", "jml_vote", "id_profile"];
    // protected $guarded = []; //tabel-tabel yang tidak boleh diisi
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/NewPertanyaanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\PertanyaanModel;

class NewPertanyaanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = PertanyaanModel::all();
        return view('konten.v_index',compact('posts'));
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('konten.v_create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //metode save
        $post = new PertanyaanModel;
        $post->isi_pertanyaan = $request['isi_pertanyaan'];
        $post->jml_vote = 0;
        $post->id_profile = 1;
        $post->save();
        
        //metode fillable & guarded
        // $post = PertanyaanModel::create([
        //     'isi_pertanyaan'=>$request['isi_pertanyaan'],
        //     'jml_vote'=>0,
        //     'id_profile'=>1,
        // ]);

        return redirect('/pertanyaan')->with('success','Pertanyaan berhasil dibuat');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = PertanyaanModel::where('id_pertanyaan',$id)->first();
        return view('konten.v_show',compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = PertanyaanModel::where('id_pertanyaan',$id)->first();
        return view('konten.v_edit',compact('post'));
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $post = PertanyaanModel::where('id_pertanyaan', $id)
                ->update([
                    "isi_pertanyaan" => $request['isi_pertanyaan']
                ]);
        return redirect('/pertanyaan',)->with('success','Pertanyaan berhasil diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $query = PertanyaanModel::where('id_pertanyaan',$id)->delete();
        return redirect('/pertanyaan',)->with('success','Pertanyaan berhasil dihapus');
    }
}

app/Http/Controllers/PertanyaanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class PertanyaanController extends Controller
{
    public function index()
    {
        $posts = DB::table('tbl_pertanyaan')->get();
        // dd($post);
        return view('konten.v_index',compact('posts'));
    }

    public function create()
    {
        return view('konten.v_create');

    }

    public function store(Request $request)
    {
        // dd($request->all());
        $request->validate([
            'isi_pertanyaan' => 'required|max:255|unique:tbl_pertanyaan'
        ]);

        $query = DB::table('tbl_pertanyaan')->insert([
            "isi_pertanyaan"    => $request['isi_pertanyaan'],
            "jml_vote"          => 0,
            "created_at"        => date('Y-m-d H:i:s'),
            "updated_at"        => date('Y-m-d H:i:s'),
            "id_profile"        => 1
        ]);

        return redirect('/pertanyaan')->with('success','Pertanyaan berhasil dibuat');
    }

    public function show($id_pertanyaan)
    {
        $post = DB::table('tbl_pertanyaan')->where('id_pertanyaan', $id_pertanyaan)->first();
        // dd($post);
        return view('konten.v_show',compact('post'));
    }

    public function edit($id_pertanyaan)
    {
        $post = DB::table('tbl_pertanyaan')->where('id_pertanyaan', $id_pertanyaan)->first();
        return view('konten.v_edit',compact('post'));
    }

    public function update($id_pertanyaan, Request $request)
    {
        $request->validate([
            'isi_pertanyaan' => 'required|max:255|unique:tbl_pertanyaan'
        ]);
        $query = DB::table('tbl_pertanyaan')
                ->where('id_pertanyaan', $id_pertanyaan)
                ->update([
                    "isi_pertanyaan"    => $request['isi_pertanyaan'],
                    "updated_at"        => date('Y-m-d H:i:s')
                ]);
        return redirect('/pertanyaan',)->with('success','Pertanyaan berhasil diupdate');
        
    }

    public function delete($id_pertanyaan)
    {
        $query = DB::table('tbl_pertanyaan')
                ->where('id_pertanyaan', $id_pertanyaan)->delete();
        return redirect('/pertanyaan',)->with('success','Pertanyaan berhasil dihapus');
        
    }

    

}

resources/views/adminlte/master.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Latihan</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{asset('/adminlte/plugins/fontawesome-free/css/all.min.css')}}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{{asset('/adminlte/dist/css/adminlte.min.css')}}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini">
<!-- Site wrapper -->
<div class="wrapper">
  <!-- Navbar -->
  @include('adminlte.partials.navbar')
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  @include('adminlte.partials.sidebar')
  
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    @yield('content')
  </div>
  <!-- /.content-wrapper -->

  <footer class="main-footer">
    <div class="float-right d-none d-sm-block">
      <b>Version</b> 3.0.5
    </div>
    <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong> All rights
    reserved.
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{{asset('/adminlte/plugins/jquery/jquery.min.js')}}"></script>
<!-- Bootstrap 4 -->
<script src="{{asset('/adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{asset('/adminlte/dist/js/adminlte.min.js')}}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{asset('/adminlte/dist/js/demo.js')}}"></script>

@stack('scripts_datatable')

</body>
</html>

resources/views/adminlte/partials/navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{{route('pertanyaan.index')}}" class="nav-link">Daftar Pertanyaan</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{{route('pertanyaan.create')}}" class="nav-link">Ajukan Pertanyaan</a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-comments"></i>
          <span class="badge badge-danger navbar-badge">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{{asset('adminlte/dist/img/user1-128x128.jpg')}}" alt="User Avatar" class="img-size-50 mr-3 img-circle">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Brad Diesel
                  <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">Call me whenever you can...</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{{asset('adminlte/dist/img/user8-128x128.jpg')}}" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  John Pierce
                  <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">I got your message bro</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{{asset('adminlte/dist/img/user3-128x128.jpg')}}" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Nora Silvester
                  <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">The subject goes here</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
        </div>
      </li>
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li>
    </ul>
  </nav>

resources/views/konten/v_create.blade.php
@extends('adminlte.master')

@section('content')
    <div class="ml-3 mt-3 mr-3 ">
      <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title">Ajukan Pertanyaan</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form role="form" action="/pertanyaan" method="POST">
          @csrf
          <div class="card-body">
            <div class="form-group">
              <label for="isi_pertanyaan">Isi Pertanyaan</label>
              <input type="text" class="form-control" id="isi_pertanyaan" name="isi_pertanyaan" placeholder="Masukkan Pertanyaan" value = "{{old('isi_pertanyaan', '')}}">
              @error('isi_pertanyaan')
                  <div class="alert alert-danger">{{ $message }}</div>
              @enderror
            </div>
          </div>
          <!-- /.card-body -->
      
          <div class="card-footer">
            <button type="submit" class="btn btn-primary">Buat Pertanyaan</button>
          </div>
        </form>
      </div>
    </div>
    
@endsection

resources/views/konten/v_edit.blade.php
@extends('adminlte.master')

@section('content')
    <div class="ml-3 mt-3 mr-3 ">
      <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title">Ajukan Pertanyaan</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
      <form role="form" action="/pertanyaan/{{$post->id_pertanyaan}}" method="POST">
          @csrf
          @method('PUT')
          <div class="card-body">
            <div class="form-group">
              <label for="isi_pertanyaan">Isi Pertanyaan</label>
              <input type="text" class="form-control" id="isi_pertanyaan" name="isi_pertanyaan" value = "{{old('isi_pertanyaan', $post->isi_pertanyaan)}}">
              @error('isi_pertanyaan')
                  <div class="alert alert-danger">{{ $message }}</div>
              @enderror
            </div>
          </div>
          <!-- /.card-body -->
      
          <div class="card-footer">
            <button type="submit" class="btn btn-primary">Update Pertanyaan</button>
          </div>
        </form>
      </div>
    </div>
    
@endsection

resources/views/konten/v_index.blade.php
@extends('adminlte.master')

@section('content')
    <div class="row">
      <div class="col-xl-12">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Daftar Pertanyaan yang Sudah Dibuat </h3>
          </div>
          <!-- /.card-header -->
          <div class="card-body">
            @if (session('success'))
                <div class="alert alert-success" role="alert">
                  {{session('success')}}
                </div>
            @endif
            <table id="example1" class="table table-bordered table-striped">
              <thead>
                <tr>
                  <th>Nomor</th>
                  <th>Isi Pertanyaan</th>
                  <th>ID Penanya</th>
                  <th>Dibuat Pada</th>
                  <th>Diupdate Pada</th>
                  <th>Jumlah Vote Saat Ini</th>
                  <th>action</th>
                </tr>
              </thead>
              <tbody>

              @forelse ($posts as $key => $isi)
                <tr>
                  <td>{{$key+1}}</td>
                  <td>{{$isi->isi_pertanyaan}}</td>
                  <td>{{$isi->id_profile}}</td>
                  <td>{{$isi->created_at}}</td>
                  <td>{{$isi->updated_at}}</td>
                  <td>{{$isi->jml_vote}}</td>
                  <td style="display: flex">
                    <a href="{{route('pertanyaan.show', ['pertanyaan'=>$isi->id_pertanyaan])}}" class="btn btn-primary btn-sm">Show</a>
                    <a href="/pertanyaan/{{$isi->id_pertanyaan}}/edit" class="btn btn-warning btn-sm">Edit</a>
                    <form action="/pertanyaan/{{$isi->id_pertanyaan}}" method="POST">
                      @csrf
                      @method('DELETE')        
                      <input type="submit" name="delete" id="delete" value='Hapus' class="btn btn-danger btn-sm">
                    </form>
                  </td>
                </tr>
              @empty
                  <td colspan="7" align="center">Tidak ada List Pertanyaan</td>
              @endforelse
                
                {{-- @foreach ($posts as $key => $isi)
                  <tr>
                    <td>{{$key+1}}</td>
                    <td>{{$isi->isi_pertanyaan}}</td>
                    <td>{{$isi->id_profile}}</td>
                    <td>{{$isi->created_at}}</td>
                    <td>{{$isi->updated_at}}</td>
                    <td>{{$isi->jml_vote}}</td>
                    <td>Field untuk Button</td>
                  </tr>
                @endforeach --}}
              </tbody>
              <tfoot>
                <tr>
                  <th>Nomor</th>
                  <th>Isi Pertanyaan</th>
                  <th>ID Penanya</th>
                  <th>Dibuat Pada</th>
                  <th>Diupdate Pada</th>
                  <th>Jumlah Vote Saat Ini</th>
                  <th>action</th>
                </tr>
              </tfoot>
            </table>
          </div>
          <!-- /.card-body -->
        </div>
      </div>    
    </div>
@endsection

@push('scripts_datatable')
<script src="{{asset('/adminlte/plugins/datatables/jquery.dataTables.js')}}"></script>
<script src="{{asset('/adminlte/plugins/datatables-bs4/js/dataTables.bootstrap4.js')}}"></script>

<script>
  $(function () {
    $("#example1").DataTable();
  });
</script>
@endpush

resources/views/konten/v_show.blade.php
@extends('adminlte.master')

@section('content')
    <div class="ml-3 mt-3 mr-3 ">
        <p>Id Penanya: {{$post->id_profile}}</p>
        <p>Pertanyaan: {{$post->isi_pertanyaan}}</p>
        <p>Tanggal Pertanyaan Dibuat: {{$post->created_at}}</p>
        <p>Tanggal Pertanyaan Diupdate: {{$post->updated_at}}</p>
        <p>Jumlah Vote untuk Pertanyaan Ini: {{$post->jml_vote}}</p>
    </div>
    
@endsection